import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sign In",
  description: "Generated by create next app",
};

export default function SignIn() {
  return <div>SignIn</div>;
}
